# Generated by Django 5.0.4 on 2024-12-09 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_product_store"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"ordering": ["username"]},
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(default="no_image.png", upload_to="products"),
        ),
        migrations.AlterField(
            model_name="product",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="app.store",
            ),
        ),
    ]
